# Testing job using black

name: Black

on:
  workflow_dispatch: {}
  workflow_call:

jobs:
  testing-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
