name: Pytest-maya2024

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/mortenbohne/maya-docker:maya2024

      - name: Set up Docker container
        run: docker run --rm -dit --name maya-container ghcr.io/mortenbohne/maya-docker:maya2024

      - name: Install requirements
        run: |
          docker exec maya-container mayapy -m pip install -r requirements.txt

      - name: Run pytest
        run: |
          docker exec maya-container mayapy -m pytest -m "not skip_on_ci" tests/
